export const listData = [
    {
        id: 1,
        title: "A Great Apartment Next to the Beach!",
        img: "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?",
        bedroom: 2,
        bathroom: 1,
        price: 1000,
        address: "456 Park Avenue, London",
        latitude: 51.5074,
        longitude: -0.1278,
    },
    {
        id: 2,
        title: "An Awesome Apartment Near the Park! Almost too good to be true!",
        img: "https://images.pexels.com/photos/1428348/pexels-photo-1428348.jpeg?",
        bedroom: 3,
        bathroom: 2,
        price: 1500,
        address: "789 Oxford Street, London",
        latitude: 52.4862,
        longitude: -1.8904,
    },
    {
        id: 3,
        title: "A New Apartment in the City!",
        img: "https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?",
        bedroom: 1,
        bathroom: 1,
        price: 800,
        address: "101 Baker Street, London",
        latitude: 53.4808,
        longitude: -2.2426,
    },
    {
        id: 4,
        title: "Great Location! Great Price! Great Apartment!",
        img: "https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?",
        bedroom: 2,
        bathroom: 1,
        price: 1000,
        address: "234 Kingsway, London,",
        latitude: 53.8008,
        longitude: 1.5491,
    },
    // {
    //     id: 5,
    //     title: "A Great Apartment Next to the Beach!",
    //     img: "https://images.pexels.com/photos/1918220/pexels-photo-1918220.jpeg?",
    //     bedroom: 2,
    //     bathroom: 1,
    //     price: 1000,
    //     address: "459 Park Avenue, London",
    //     latitude: 51.5054,
    //     longitude: -0.1288,
    // },
    // {
    //     id: 6,
    //     title: "An Awesome Apartment Near the Park! Almost too good to be true!",
    //     img: "https://images.pexels.com/photos/1428330/pexels-photo-1428330.jpeg?",
    //     bedroom: 3,
    //     bathroom: 2,
    //     price: 1500,
    //     address: "799 Oxford Street, London",
    //     latitude: 52.4892,
    //     longitude: -1.8994,
    // },
    // {
    //     id: 7,
    //     title: "A New Apartment in the City!",
    //     img: "https://images.pexels.com/photos/2062450/pexels-photo-2062450.jpeg?",
    //     bedroom: 1,
    //     bathroom: 1,
    //     price: 800,
    //     address: "100 Baker Street, London",
    //     latitude: 53.4868,
    //     longitude: -2.2486,
    // },
    // {
    //     id: 8,
    //     title: "Great Location! Great Price! Great Apartment!",
    //     img: "https://images.pexels.com/photos/2467270/pexels-photo-2467270.jpeg?",
    //     bedroom: 2,
    //     bathroom: 1,
    //     price: 1000,
    //     address: "239 Kingsway, London,",
    //     latitude: 53.8098,
    //     longitude: 1.5411,
    // }
        

]